"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "bootstrap/dist/css/bootstrap.min.css";
// import { useEffect } from "react";
import { DM_Sans } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans", // Use CSS variables
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // useEffect(() => {
  //   import("bootstrap/dist/js/bootstrap.bundle.min.js"); // Dynamically load JS
  // }, []);

  return (
    <html lang="en">
      <body>
        {/*  className={`${geistSans.variable} ${geistMono.variable} antialiased`} */}
        {children}
      </body>
    </html>
  );
}
